### ISSUE TITLE
Can't Right click on a news or copy an URL

### ISSUE THREAD

**Issue by Martyprod** [Xyrio/RSSOwlnix#104] opened 2020-10-21 15:47 UTC
Hello, 

In the original RSSOwl, i could in a news, right click on the page and do stuff like "copy shortcut" etc... when i try with RSSowlnix, there is only a small 4 item menu, with Reload, etc...

Is there a way to have a menu like it was before, who is i think the one from Chrome etc.. Thanks ! No matter which reader i use (the internal one, or the chrome one); it's the same menu which appears when right clicking. Thanks.

**Comment by Xyrio** [comment] 2020-10-22 17:35
yea thats broken duplicate of #48

**Closed by Xyrio** 2020-10-22 17:35 UTC
