### ISSUE TITLE
Duplicate feeds

### ISSUE THREAD

**Issue by Neustradamus** [Xyrio/RSSOwlnix#40] opened 2019-02-12 18:06 UTC
We can add always feeds, it is possible to do not add if it is already?

**Comment by Xyrio** [comment] 2019-02-12 19:46
try: preferences / feeds / reading / automatically mark duplicate news as read

**Comment by Neustradamus** [comment] 2019-02-12 22:43
Why this?
It is not about news but about feeds

**Comment by Xyrio** [comment] 2019-02-13 07:48
being able to add the same one multiple times is a feature. sometimes you want the same feed in different folders. the news are recognized as being duplicates then and whatever you do in one of those copies happens in all other copies as well. i dont see the problem here.

**Comment by Xyrio** [comment] 2019-02-13 08:05
seem this is a duplicate of #34. continue there

**Closed by Xyrio** 2019-02-13 08:05 UTC
